# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d4a076b4642b74cbba3996be99f34c48f8aa8145ebd797da8f805b4935683f761c363b711e5bdf54526aed2a358524cc6f0576a326654a8250b9140efd599b

test:
  secret_key_base: 2bc74538998fe33f9529f63a57ed0ed1ac3f3bbcb4a0b24466ab668add33dfa71e8418dec351afd8ee536cebf11c01d57a68bdb20335a68b24faa1ede681c242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
